name: Build Ares Kernel with KernelSU

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOOT_IMG_URL: ${{ secrets.BOOT_IMG_URL }}
      KERNEL_SU_REPO: https://github.com/tiann/KernelSU
    steps:
    - name: ðŸ—ƒï¸ Download boot.img
      run: curl -L "$BOOT_IMG_URL" -o boot.img
    - name: ðŸ›  Install tools
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex libelf-dev libncurses-dev git unzip zip
    - name: Extract kernel config
      run: |
        curl -O https://raw.githubusercontent.com/torvalds/linux/master/scripts/extract-ikconfig
        chmod +x extract-ikconfig
        ./extract-ikconfig boot.img > ares_defconfig
    - name: ðŸ“‚ Clone kernel source
      run: |
        git clone --depth=1 https://github.com/RedmiK40Gaming/ares-kernel.git kernel
        mv ares_defconfig kernel/arch/arm64/configs/ares_defconfig
    - name: âœ… Kernel configuration
      run: |
        cd kernel
        make O=out ARCH=arm64 ares_defconfig
    - name: ðŸ”§ Apply KernelSU
      run: |
        cd kernel
        git clone --depth=1 "$KERNEL_SU_REPO" kernelsu
        # Configure KernelSU as per its docs
    - name: ðŸ§± Build kernel
      run: |
        cd kernel
        export ARCH=arm64
        export CLANG_PATH=/usr/bin
        make -j$(nproc) O=out ARCH=arm64 CC=clang
    - name: ðŸ“¦ Package with AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3 ak3
        cp kernel/out/arch/arm64/boot/Image.gz-dtb ak3/
        cd ak3
        zip -r Ares-KernelSU.zip *
    - name: âœ… Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: Ares-KernelSU
        path: ak3/Ares-KernelSU.zip
